### ISSUE TITLE
Island Wall Count counts faces after Solidify is applied

### ISSUE THREAD

**Issue by EntityinArray** [lshawau/Blender-Maze-Generator#1]
Island Wall Count takes faces created by Solidify modifier into account.
Steps to reproduce:
1. Make sure Delete Islands is enabled
2. Set Island Wall Count to 50
3. Toggle Solidify
4. Observe maze walls appear and disappear

**Comment by lshawau** [comment]
Intended, the maze should **never** generate with 50+ connected walls without solidify, expect the entire maze to disappear without solidify and high delete islands count - Delete islands is really there to remove very small features - single length walls etc. But I felt it had some use for more randomisation so exposed the value for the user.
